name: Run test cases

on: [push, pull_request]

jobs:
    run_test_cases:
        runs-on: ubuntu-latest

        container:
            image: erlang:22.1

        steps:
            - uses: actions/checkout@v2
            - name: Dialyzer
              run: rebar3 dialyzer
            - name: Test
              run: rebar3 eunit
